### ISSUE TITLE
css snippets dont work

### ISSUE THREAD

**Issue by siduck** [olrtg/emmet-language-server#12]
the css shortcuts here dont work

https://docs.emmet.io/cheat-sheet/

**Comment by olrtg** [comment]
Hey @siduck ! can you show me how are you setting up this language server, the version of the package and maybe some `LspInfo` output?

**Comment by siduck** [comment]
hi @olrtg 

`require("lspconfig").emmet_language_server.setup()`

and i installed the lsp from mason

![image](https://github.com/olrtg/emmet-language-server/assets/59060246/ffa7aa91-bc44-436a-8c32-2ce46fdd73bc)

**Comment by siduck** [comment]
oh nvm i'm dumb, almost css work 

i first tried bg+

![image](https://github.com/olrtg/emmet-language-server/assets/59060246/6b22bd02-f983-48a6-8108-468f00cb28ee)

seems like its bg#fff then it'll autocomplete

Sorry for wasting your time

**Comment by siduck** [comment]
Although the "m" snippet ( margin )  isnt shown in cmp window

![image](https://github.com/olrtg/emmet-language-server/assets/59060246/4098099f-1456-409e-af54-16aa3842f7e7)


i'm assuming its pushed at the end!  Ik this issue is cmp related, but do you know if i could prioritize emmet lsp's completion?

**Comment by olrtg** [comment]
@siduck no problem!

Hmm isn't `margin: ;` the snippet for `m`?
