### ISSUE TITLE
Lsp is not working in Helix

### ISSUE THREAD

**Issue by youngmoguler** [olrtg/emmet-language-server#16]
After doing according to this repos readme. Every config is fine from my end also done the installation of the emmet-language-server but still it didn't work. Is it because of the path declaration of that npm module which isn't getting activated or what? Because I saw this behavior after installing any npm package globally and done a hx --health [language] to check and there I saw that package by default wasn't showing for that particular. So, to solve that I only installed lsps that are providing homebrew command.

I'm using helix --head and below is my configs->
[language-server.emmet-ls]
args = ["--stdio"]
command = "emmet-language-server"

language-servers = [ "typescript-language-server", "tailwindcss-react", "eslint", "emmet-ls" ]

For HTML ->
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-react", "emmet-ls"]

**Comment by olrtg** [comment]
Hey! are you sure the `emmet-language-server` command is in your PATH? Try running `emmet-language-server --stdio` in your command line and the program should stay like this:

![image](https://github.com/olrtg/emmet-language-server/assets/20072509/c4e04e82-eadf-4fd3-8820-a07630acba10)

If you get an error it won't work with helix even though your config is right.

**Comment by youngmoguler** [comment]
Thank you, your solution worked✨.
