### ISSUE TITLE
Add support for `emmet.extensionsPath`

### ISSUE THREAD

**Issue by UrNightmaree** [olrtg/emmet-language-server#17]
As the title said, add support for `emmet.extensionsPath` when setting up LSP with `init_options`

**Comment by olrtg** [comment]
Hey @UrNightmaree! I saw your issue that day but I'm busy with work. I'm going to take a look at this over the weekend probably.

**Comment by olrtg** [comment]
Little update! I'm almost there with the feature. Will keep working in during the week on this.

**Comment by olrtg** [comment]
https://www.npmjs.com/package/@olrtg/emmet-language-server/v/2.4.0

Update your package! 🤘🏽

**Comment by UrNightmaree** [comment]
Alright, thank you!
