### ISSUE TITLE
css.intUnit Configuration does not take effect

### ISSUE THREAD

**Issue by kola-web** [olrtg/emmet-language-server#18]

**Comment by olrtg** [comment]
Well I've put this in my config and it seems that is working:

```
preferences = {
  ["css.intUnit"] = "rem",
},
```

![image](https://github.com/olrtg/emmet-language-server/assets/20072509/6d8eac5d-9b7b-4607-9c6b-64ff1e19441a)

**Comment by kola-web** [comment]
thank you

**Comment by kola-web** [comment]
@olrtg Ask a question
Why must we set ["css.intUnit"] = "rem",
Don’t you want to set css={intUnit="rem"} like this?

**Comment by olrtg** [comment]
Hey @kola-web! Hmm.. I guess that'll be nice but now I'm just passing the config to the emmet-helper as is so that's why it is the way it is right now. Will think about it more though! Great question.

**Comment by kola-web** [comment]
Thanks for your quick reply
