### ISSUE TITLE
Setup with nvim-lspconfig doesn't work

### ISSUE THREAD

**Issue by xuanhung1509** [olrtg/emmet-language-server#2]
Using the provided nvim-lspconfig setup, I encoutered an error: `[lspconfig] Cannot access configuration for emmet_language_server. Ensure this server is listed in 'server_configuration.md' or added as custom server.`

Setup with autocmd does work though. However, I'd like the lsp stuffs being in a single place, so I prefer setting up with nvim-lspconfig.

I then came up with this config.

```lua
local lspconfig = require "lspconfig"
local configs = require "lspconfig.configs"

if not configs.emmet_language_server then
  configs.emmet_language_server = {
    default_config = {
      filetypes = {
        "html",
        "css",
        "scss",
        "javascript",
        "javascriptreact",
        "typescriptreact",
        "svelte",
      },
      cmd = { "emmet-language-server", "--stdio" },
      root_dir = lspconfig.util.root_pattern ".git",
      init_options = {
        --- @type table<string, any> https://docs.emmet.io/customization/preferences/
        preferences = {},
        --- @type "always" | "never" defaults to `"always"`
        showexpandedabbreviation = "always",
        --- @type boolean defaults to `true`
        showabbreviationsuggestions = true,
        --- @type boolean defaults to `false`
        showsuggestionsassnippets = false,
        --- @type table<string, any> https://docs.emmet.io/customization/syntax-profiles/
        syntaxprofiles = {},
        --- @type table<string, string> https://docs.emmet.io/customization/snippets/#variables
        variables = {},
        --- @type string[]
        excludelanguages = {},
      },
    },
  }
end

lspconfig.emmet_language_server.setup {
  on_attach = on_attach,
  capabilities = capabilities,
}
```

Anyway, it's still a lot nicer if I could set this up without having to manually add and explicitly pass default options.

**Comment by olrtg** [comment]
Hey @xuanhung1509 ! I'll check this out tomorrow.. In theory the PR was merged but I haven't tried to use it in my personal setup. Will keep you posted 🤘🏽

**Comment by xuanhung1509** [comment]
yep, I'm using Nvchad fyi.

**Comment by olrtg** [comment]
Ok! so in the mean time make sure that you have the commit that adds the `emmet_language_server` package to lspconfig here https://github.com/neovim/nvim-lspconfig/commits/master

**Comment by xuanhung1509** [comment]
Wait, haven't you already did that in [#2702](https://github.com/neovim/nvim-lspconfig/pull/2702)? Am I missing sth?

**Comment by xuanhung1509** [comment]
Thanks! It works now after updating to the latest commit
