### ISSUE TITLE
Self-closing tag weird behaviour

### ISSUE THREAD

**Issue by kuator** [olrtg/emmet-language-server#22]
It's not necessarily an emmet_language_server problem, but I don't know where to ask this, so I'm asking here.
Setting filetype to `javascript` in neovim, emmet_language_server doesn't self-close it.
But with filetype set to `javascriptreact`, it closes it as advertised.
Here's the gif to illustrate this:

![Peek 2023-11-15 21-41](https://github.com/olrtg/emmet-language-server/assets/25168308/5f8a3a4a-677f-446b-a1f2-79574188f058)

**Comment by olrtg** [comment]
Hey! you have two options:

- Add `"javascript"` to your file type list. Files with the `.js` extension are always recognized as `javascript`.
- Rename your file extension to `.jsx`. Files with the `.jsx` extension are always recognized as `javascriptreact`.

Hope that helps!

**Comment by kuator** [comment]
> Hey! I recommend you to rename your file extension to `.jsx`. Files with the `.jsx` extension are always recognized as `javascriptreact` (and are treated as `jsx` by the emmet package). The `javascript` filetype is treated as `html` by the language server, and in `html` the concept of self-closing tags doesn't really exist for regular tags like `div`s.
> 
> Hope that helps!

Unfortunately, it's a convention used at my company 🥲. I'm gonna discuss it with my management. Thank you for pointing out the problem

**Comment by olrtg** [comment]
Yeah maybe you can discuss it with your team, I think vscode doesn't provide emmet completions in .js files either. So I should be a win for both neovim and vscode users. And you can find on the internet scripts to rename only .js files that contain jsx to .jsx.

And maybe in the mean time you can create an autocommand for javascript files to set the filetype to `javascriptreact`.
