### ISSUE TITLE
Can't prompt CSS in vue files

### ISSUE THREAD

**Issue by kola-web** [olrtg/emmet-language-server#23]
Reproduction method
1. Create a vue file
```vue
<template>
  <div></div>
</template>

<script>
export default {
  name: "a",
};
</script>

<style lang="scss" scoped>
div {
}
</style>
```
2. No prompt will appear when entering the css abbreviation in the scss section.
![image](https://github.com/olrtg/emmet-language-server/assets/46446884/1f2324c2-feb8-4d66-a4e4-81312617fc15)

**Comment by olrtg** [comment]
Hey! You're right.

I will check that out when I have some spare time.

**Comment by kola-web** [comment]
Thank you for your work
