### ISSUE TITLE
Usage via `omnifunc` 

### ISSUE THREAD

**Issue by lcmen** [olrtg/emmet-language-server#24]
Hey!
Thank you for writing this plugin. I would like to use it with Neovim without any additional autocomplete plugins.

I've copied the configuration from the readme but I can't this plugin work with built-in autocomplete. I have a following `on_attach` function that connects `omnifunc` with `lsp.omnifunc` for the buffer:

```lua
local on_attach = function(client, bufnr)
    local map = vim.api.nvim_buf_set_keymap
    local ion = vim.api.nvim_buf_set_option
    local opts = { noremap = true }

    ion(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    ion(bufnr, 'formatexpr', 'v:lua.vim.lsp.formatexpr()')

    -- Configure keybindings for LSP
    map(bufnr, 'n', 'C-y', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
    map(bufnr, 'n', 'g0', '<Cmd>lua vim.lsp.buf.document_symbol()<CR>', opts)
    map(bufnr, 'n', 'gf', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    map(bufnr, 'n', 'gi', '<Cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    map(bufnr, 'n', 'gt', '<Cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    map(bufnr, 'n', 'gr', '<Cmd>lua vim.lsp.buf.references()<CR>', opts)
    map(bufnr, 'n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
end
```

Now, if I type valid emmet syntax in the HTML file (e.g. `h1.center`), and hit `CTRL+x`, `CTRL+o`, I see a following message in status line:

```
^X mode (^]^D^E^F^O^K^L^N^O^Ps^U^V^Y) Pattern not found
```

How can I force emmet to convert snippet to a proper HTML structure?

**Comment by olrtg** [comment]
Hey! I don't really know much about omni completion since I just use nvim-cmp with LuaSnip (this language server just provides snippet completion).

I know that now we have a new built-in API to work with snippets https://github.com/neovim/neovim/pull/25301. Maybe you can check that out.

Hope that helps!

**Comment by lcmen** [comment]
Thank you @olrtg , is there a way I can hook up this plugin to `LuaSnip` without `nvim-cmp`?

**Comment by olrtg** [comment]
Sorry, I don't know. 😢 Maybe https://www.reddit.com/r/neovim/comments/rddugs/snipcomplua_luasnip_companion_plugin_for_omni/?
