### ISSUE TITLE
Not run on xml file.

### ISSUE THREAD

**Issue by foolishprogrammer** [olrtg/emmet-language-server#26]
I install the plugin from mason on lazyvim, but the plugin do not work on xml file. It works fine as expected on html file, but because most of the time i work with xml data, this kinda bother me have to use vscode only to works with xml file.

**Comment by olrtg** [comment]
Hey! Did you try to add XML as a valid `filetype`?

**Comment by olrtg** [comment]
Any news? 👀

**Comment by foolishprogrammer** [comment]
> Any news? 👀

Hi, sorry for not confirming. I just recently going back to remake my nvim config from scratch rather than using the default from lazyvim. Adding the filetype works. Sorry for not confirming until now. I use the method using the nvim api rather than lspconfig as i still not quite understand the lspconfig setup completely..
