### ISSUE TITLE
Question about adding filetypes 

### ISSUE THREAD

**Issue by Redoxahmii** [olrtg/emmet-language-server#27]
i am using LazyVim in neovim and i have created a lsp-config.lua in the plugins directory for changing the filetypes as i needed to add `vue` to the filetype 
`return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        emmet_language_server = {
          filetypes = {
            "css",
            "eruby",
            "html",
            "javascript",
            "javascriptreact",
            "less",
            "sass",
            "scss",
            "pug",
            "typescriptreact",
            "vue",
          },
        },
      },
    },
  },
}`
The reason i have all the types mentioned is because only adding vue made it stop working on other formats and wanted to ask if setting it up like this will also cause issue with other default configurations that are provided by emmet-language-server and if i should add those here as well.
Thank you in advance and love yours over emmet_ls.

**Comment by olrtg** [comment]
Hey @Redoxahmii! Thanks for the kind words.

No, only the properties that you pass in the table will get overwritten.

Aside from that, take a look at #25. If you're using something like volar as a language server you don't need this language server for vue files since volar already bundles emmet in their language server.

Closing this issue for now. Feel free to re-open if you need more help.
Have a good one!

**Comment by Redoxahmii** [comment]
> Hey @Redoxahmii! Thanks for the kind words.
> 
> No, only the properties that you pass in the table will get overwritten.
> 
> Aside from that, take a look at #25. If you're using something like volar as a language server you don't need this language server for vue files since volar already bundles emmet in their language server.
> 
> Closing this issue for now. Feel free to re-open if you need more help. Have a good one!

Thank you for the info i changed my lsp to volar from vetur and  it does bundle with emmet. i guess i wasted time finding out how to include filetypes :smile:

**Comment by Redoxahmii** [comment]
> No worries man! if you still want to use vetur you can add `vue` to your `filetypes` table (keeping the other default languages in the list).

I will test out volar as most suggest that to be better. It has a little issue with tsserver but disabling tsserver and attaching volar for .ts files seems to work. I guess they are also bundling typescript too.

**Comment by olrtg** [comment]
Yes! Volar bundles all of that stuff for you. Taking a quick look to volar's codebase these are the services that they're bundling already https://github.com/vuejs/language-tools/blob/f0d1af77635b882ba092b7c40d8720f8b3aa0db3/packages/language-service/src/languageService.ts#L12C1-L19C89
