### ISSUE TITLE
lspconfig setup not working

### ISSUE THREAD

**Issue by sixtusagbo** [olrtg/emmet-language-server#3]
I installed emmet-language-server with Mason, I'm getting this error after enabling the server in my lspconfig.lua file: [lspconfig] Cannot access configuration for emmet_language_server. Ensure this server is listed in 'server_configuration.md' or added as custom server

**Comment by mmirus** [comment]
You may need to ensure you have updated lspconfig to include the commit that added support for this server. See #2.

**Comment by sixtusagbo** [comment]
How do I go about that, I just started using neovim and nvchad recently. I have tried to update the plugin with Mason but afterwards the issue still persists. Is there a way to specify recent commit or force it to download a certain ref or so?

**Comment by gegoune** [comment]
It's an issue with nvchad having outdated lspconfig plugin. You most likely would be way better of using your own configuration.

**Comment by olrtg** [comment]
That's a problem that other distros (e.g: LunarVim, which is the one I use) suffer from.. so maybe you can just wait until they bump their core deps to a version that includes the addition of the `emmet_language_server` and then remove that conditional from your setup.

**Comment by sixtusagbo** [comment]
Okay, thanks pal.

**Comment by MattiaSilvestri** [comment]
Hi, I'm using AstroNvim and I'm getting the same error, adding the conditional statement mentioned before didn't help (even tho I'm not sure I added it in the right place, I'm not super familiar with neovim config structure yet). I also updated lspconfig to the latest version but nothing changed. Is there anything else I can try?

**Comment by olrtg** [comment]
Hey @MattiaSilvestri ! did you get an error or something like that?

**Comment by MattiaSilvestri** [comment]
Hi, yes I get this error in addition to the one mentioned from OP: 
`/home/mattia/.config/nvim/lua/astronvim/utils/lsp.lua:387: attempt to index field 'document_config' (a nil value)`

**Comment by olrtg** [comment]
@MattiaSilvestri did you try passing an empty table to the lspconfig setup function? See #11

**Comment by sixtusagbo** [comment]
@MattiaSilvestri I don't use Astrovim but if there setup is similar, then you can try passing the setup config manually, that's how I solved the issue on NeoVim. With time, when they update theirs then you can remove the manual setup.
