### ISSUE TITLE
Expand emmet snippets

### ISSUE THREAD

**Issue by Caddy121** [olrtg/emmet-language-server#31]
Does anyone know how to set up nvim-lsp so that I can expand emmet with ctrl + h?

**Comment by Caddy121** [comment]
> Can you add more context on what you want to achieve?

If I type "test", I'd want to hit ctrl+h (or whichever key map I assigned) to expand it to <test></test> without having to look through cmp list to choose what I want. Sometimes the cmp list is filled with stuff and I'd have to search for what I want. I am not sure if this is an emmet thing or more of a cmp thing.

**Comment by olrtg** [comment]
Hey @Caddy121.. yeah someone reported this already in #28. It was then moved to https://github.com/olrtg/nvim-emmet/issues/1 where you can see the resolution of this issue in particular.
