### ISSUE TITLE
Astro support? 

### ISSUE THREAD

**Issue by 0bCdian** [olrtg/emmet-language-server#34]
First of all, I want to thank you for this excellent plugin! I don't know if this is the right place to ask for this but your emmet wrap plugin seems to not work on .astro files, the popup is created but nothing happens after you press enter and I wanted to know if there is something I'm missing or if there is an incompatibility issue, everything else about emmet works with my lsp, like snippets and all of emmet goodness, just this specific thing doesn't work. Thanks again, and sorry if this is a dumb issue.

**Comment by olrtg** [comment]
Hey @0bCdian no worries and thanks for the kind words! You don't need to use this language server for Astro, the Astro language server already comes with emmet bundled, check #25.

Let me know if that fixes the issue for you.

**Comment by 0bCdian** [comment]
This solved my issue, thanks for taking the time to respond!
