### ISSUE TITLE
Is there a way to use a `snippets.json` file?

### ISSUE THREAD

**Issue by Agent-E11** [olrtg/emmet-language-server#36]
Pretty much just the title.

I am using Neovim with lsp-config.

I have tried this:
```lua
lsp_conf.emmet_language_server.setup({
    extensionsPath = {
        init_options = {
            os.getenv("HOME") .. "/emmet-extensions"
        }
    }
})
```

And this is `$HOME/emmet-extensions/snippets.json`:
```json
{
    "html": {
        "snippets": {
            "test": "div{test}"
        }
    }
}
```

**Comment by olrtg** [comment]
The `extensionsPath` key should go inside of `init_options` not the other way around.

**Comment by Agent-E11** [comment]
> The `extensionsPath` key should go inside of `init_options` not the other way around.

🤦 My bad, that was dumb of me. But, after switching them, it still isn't working:
```lua
lsp_conf.emmet_language_server.setup({
    init_options = {
        extensionsPath = {
            os.getenv("HOME") .. "/emmet-extensions"
        }
    }
})
```

**Comment by Agent-E11** [comment]
Also, is there a default path that I can use just to get it working?

**Comment by olrtg** [comment]
Hey @Agent-E11! no worries. I don't really use that feature but from what I remember you can pass relative and absolute paths of folders. I have tested using relative paths, so you can try that and if it works the absolute path resolution is not working or something like that. Let me know!

**Comment by Agent-E11** [comment]
Ok, thank you.

Is the relative path relative to the root directory detected by the lsp? (When I rin`:LspIngo`, there is a "root directory" field that it displays).

And is there a setting I can set just so I know that the lsp is even using the config I am setting?

**Comment by olrtg** [comment]
You're welcome! No, not really, there's no way currently of knowing that. The root directory that you mention is probably just the current working directory (which is normally where your .git folder is). I may have to check that feature again. For now I'll close this and create another issue in case the absolute paths don't work, but will do that after some testing in the following week.

**Comment by Agent-E11** [comment]
It seems to just be mostly working now, I don't know why. Here is my config:
```lua
lsp_conf.emmet_language_server.setup({
    init_options = {
        extensionsPath = {
            os.getenv("HOME") .. "/.emmet-extensions",
            "."
        }
    }
})
```

The only problem is that it isn't displaying the completion in the dropdown before I type the whole thing out. e.g. I have a completion called `script:htmx` and if I type `script:htm` and accept the completion, it expands to `<script:htm></script:htm>`, if I type the full name, it expands to the full thing defined in `.emmet-extensions/snippets.json`
