### ISSUE TITLE
Missing or malfunctioned completion with emmet-language-server

### ISSUE THREAD

**Issue by mellash** [olrtg/emmet-language-server#38]
Here is my lsp config, and I did't really know if it is lsp or emmet-language-eserver causing the problem.

```vim
call LspAddServer([#{name: 'emmet',
                 \   filetype: ['html', 'htm'],
                 \   path: '/home/mellash/.npm-global/bin/emmet-language-server',
                 \   args: ['--stdio'],
                 \ }])
```

Here is a screenshot of the completion

![lsp](https://github.com/olrtg/emmet-language-server/assets/162956766/11058b6c-be5d-40c8-a6e6-07fa8d95ac8f)

**Comment by olrtg** [comment]
Hey! I can't really reproduce what you're saying.

<img width="343" alt="Screenshot 2024-05-09 at 11 16 22" src="https://github.com/olrtg/emmet-language-server/assets/20072509/f06e308d-7af0-4eb9-a996-992f5e5b0bda">

Maybe double-check your lsp configuration?
