### ISSUE TITLE
Emmet suggestions for components

### ISSUE THREAD

**Issue by Tauromachian** [olrtg/emmet-language-server#43]
First I wanted to thank you for your LS. It's been very useful.

Is there a way in which I can configure the LS is to autocomplete for React or Vue component syntax.

For example, if I type `AppCard>div` it should be completed to this:
```
<AppCard>
  <div></div>
</AppCard>
```
Is this possible?

**Comment by olrtg** [comment]
Hey @Tauromachian in `tsx`/`jsx` files you should get that completion, take a look:

![CleanShot 2024-07-26 at 13 42 43@2x](https://github.com/user-attachments/assets/0f0000d5-f43e-43f2-a60c-6a0c00dfad0a)

But for Vue you should use only the vue language server (volar). Look at #25.

Hope that helps!

**Comment by Tauromachian** [comment]
@olrtg Thanks for taking the time to answer. Closing this issue.
