### ISSUE TITLE
Emmet suggestions don't appear

### ISSUE THREAD

**Issue by dhymasriyanto** [olrtg/emmet-language-server#44]
Thanks for ur great work but I think I have some problems

I am using:
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```
And I am install it using nvim-lsconfig, which I install using vim-plug.

When I type html tags in index.html or react typescript files, the suggestions don't seem to appear.
![image](https://github.com/user-attachments/assets/7a65c553-c88b-46a6-9b02-e9a2cd08b340)

I try to `:LspInfo`, the output is:
![image](https://github.com/user-attachments/assets/57709270-121b-4986-bf65-790878fc5b24)

Is there a step I missed? Or is there a way to use this extension? Thanks!

**Comment by olrtg** [comment]
Hey! what's your node version? can you check if it's up to date?

**Comment by dhymasriyanto** [comment]
Hello this is my node version and npm


![image](https://github.com/user-attachments/assets/9b6e8224-0b2c-415f-a9c7-b4a4aeb6838c)

![image](https://github.com/user-attachments/assets/9261a8a9-f3bf-4793-90cb-8e5dc53d0b97)

**Comment by olrtg** [comment]
Ok that's fine! And what about your `LspLog`? do you have any errors related to emmet?

**Comment by olrtg** [comment]
Also check if you can execute `emmet-language-server --stdio` in your terminal

**Comment by dhymasriyanto** [comment]
> Ok that's fine! And what about your `:LspLog`? do you have any errors related to emmet?

This is my ```LspLog``:`
![image](https://github.com/user-attachments/assets/127b35c6-c62b-4ce6-a977-b6219b4bfbfe)


> Also check if you can execute `emmet-language-server --stdio` in your terminal


and ```emmet-language-server --stdio```:
![image](https://github.com/user-attachments/assets/db79bb9d-2147-4120-92a1-10a389a296dd)

**Comment by olrtg** [comment]
Hmmm that's weird.. I can you're using a nvim distro make sure to install it with `:Mason` and remove the global package just in case the distro is trying to get the executable from the mason path.

Other than that I don't see anything wrong. Also another question, what are you're using for your cmp engine?
