### ISSUE TITLE
Not working with PHP

### ISSUE THREAD

**Issue by rcardoso20** [olrtg/emmet-language-server#46]
Hello.

I can't seem to make it work with the filetype .php, do I have something wrong in the config?

``` lua
["emmet_ls"] = function()
    -- configure emmet language server
    lspconfig["emmet_ls"].setup({
        capabilities = capabilities,
        filetypes = { "css", "eruby", "html", "javascript", "javascriptreact", "less", "sass", "scss", "pug", "typescriptreact", "php" },
        init_options = {
            includeLanguages = {
                php = "html"
            },
            showAbbreviationSuggestions = true,
            showExpandedAbbreviation = "always",
            showSuggestionsAsSnippets = true,
        },
    })
end,
```
It's working with .html files but with .php files only the intelephense LSP gets attached.
I am probably doing something wrong right?

**Comment by olrtg** [comment]
Hey! it seems that you're using other language server. It should be `emmet_language_server`. Check the README just in case.

**Comment by olrtg** [comment]
No worries man! happens to all of us 🤘🏽 

Closing this then! good luck.
