### ISSUE TITLE
Emmet suggestions don't appear in cmp on 2.0.2

### ISSUE THREAD

**Issue by mmirus** [olrtg/emmet-language-server#5]
Hi there - when I update from 2.0.1 to 2.0.2, I no longer receive Emmet suggestions in cmp. Downgrading to 2.0.1 again fixes the problem.

Please let me know if I can provide any additional information or help test anything.

**Comment by olrtg** [comment]
Hey @mmirus! yeah you're right.. it broke in 2.0.2.. I did another release that fixes this so please update to the latest version.

Thanks for reporting. Feel free to reopen if you still have problems after updating.

**Comment by mmirus** [comment]
It's working now. Thank you!
